rootProject.name = "android-pedestal"
include(":app")
// 业务层
include(":launcher")
project(":launcher").projectDir = file("business/launcher")
include(":home")
project(":home").projectDir = file("business/home")
include(":home_api")
project(":home_api").projectDir = file("business/home_api")
include(":auth")
project(":auth").projectDir = file("business/auth")
include(":auth_api")
project(":auth_api").projectDir = file("business/auth_api")
include(":common")
project(":common").projectDir = file("business/common")
// 中台层
include(":banner")
project(":banner").projectDir = file("middle/banner")
include(":imagepicker")
project(":imagepicker").projectDir = file("middle/imagepicker")
include(":citypicker")
project(":citypicker").projectDir = file("middle/citypicker")
// platform 层
include(":core")
project(":core").projectDir = file("platform/core")
include(":log")
project(":log").projectDir = file("platform/log")
include(":network")
project(":network").projectDir = file("platform/network")
include(":statistics")
project(":statistics").projectDir = file("platform/statistics")
include(":imageloader")
project(":imageloader").projectDir = file("platform/imageloader")
