rootProject.name = "android-pedestal"
include(":app")
// 业务层
include(":launcher")
project(":launcher").projectDir = file("business/launcher")
include(":common")
project(":common").projectDir = file("business/common")
// 中台层
include(":auth")
project(":auth").projectDir = file("zhongtai/auth")
include(":auth_api")
project(":auth_api").projectDir = file("zhongtai/auth_api")
include(":imagepicker")
project(":imagepicker").projectDir = file("zhongtai/imagepicker")
// platform 层
include(":core")
project(":core").projectDir = file("platform/core")
include(":log")
project(":log").projectDir = file("platform/log")
include(":network")
project(":network").projectDir = file("platform/network")
include(":statistics")
project(":statistics").projectDir = file("platform/statistics")
include(":imageloader")
project(":imageloader").projectDir = file("platform/imageloader")
